name: tests

on:
  push:
  pull_request:

jobs:
  doctest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requests
        run: pip install requests

      - name: Run doctests
        run: python -m doctest wardial.py -v